dist: xenial
language: go
go:
- 1.11
env:
- PATH=/home/travis/gopath/bin:$PATH
script:
- "! gofmt -d . | read"
- go test -v ./...
before_deploy:
- rm -Rf ./dist
- go get github.com/mitchellh/gox
- gox -ldflags="-X main.branch=$TRAVIS_TAG -X main.revision=$TRAVIS_COMMIT" -osarch="linux/amd64 
  linux/386 linux/arm darwin/amd64 darwin/386" -output="dist/{{.OS}}_{{.Arch}}_{{.Dir}}"
deploy:
  provider: releases
  api_key:
    secure: AXhg+m8loR8mQZMK1T+rWvK4yiOmfdUvGFl8MIjwINaSh7NXMR2mqRB1Kx0UgEAdYhkkevp9NjJscedha9vQmPmiTxImn4Mr3S1hfLBfWKjmTkpe2itSARJLwzpv09skay1q7dbBpZ7t2Xwe4HExuX1vlkU6Kixv3Z+GlUgkmH3c1db4h01ANLbCdabtBQaqjfh7OMteNg2fBAKxANfoNPAVzD8PzIcm9ffvU9BEW6UKVMIxc5yygVBlaGqyu6JcKvWRaT9JfDF1G0iJVawy1jSfhlMUeRfA2aDEE+ne1meLp6KD0JqocXy+t1fZejlAcYVJigmdeMpQXsfKgXtQ1hLE/6wIqP3CzBX4/6x2FDHh2Mb9IfjKjH5mlUvk7vQpbfmN7k04YXuugczCZS7fm3pTPkZgnLNrdCx6miAi/G84ssO3vaMpW3uYOlcmsESBAYNkVFLzkw4ggfwBFWkK3s81CxUaUxxH15vuvYLejvBWkFgCDTLq2Kmn1bbts9xx9v1hGtEtqLwYq1HVMXxs507zJqpvQKVD8DsWC6kqp7+dzIGNEi0ixqM3lZVKU5iqC8mXkw7HMZZ3jOE+YbTFOxrMqJrbS5z9eFSe37Wz7cFfpb4Z7YXSy3E8JMKMcu9L8mxtHFOm9AUC1v3ySMz9zI3kqy+6zs2Axb+LjLSzPBw=
  file: 
    - dist/linux_amd64_irccat
    - dist/linux_386_irccat
    - dist/linux_arm_irccat
    - dist/darwin_amd64_irccat
    - dist/darwin_386_irccat
  skip_cleanup: true
  on:
    tags: true
